### ISSUE TITLE
Miners Fee spend before upload

### ISSUE THREAD

**Issue by alberm** [DECENTfoundation/DECENT-Network#197]
The Miners fee is subtracted from the owners account before the upload is confirmed. In case the upload fails the complete fee is spend.  My upload still says uploading but the DCT for storing and distributing the file are spend.
Are there plans to create an escrow account?

**Comment by ejossev** [comment]
The escrow is implemented from the beginning. The remaining part is in the "publishing_fee_escrow" and is paid back at the content expiration (you can shorten it with canceling the content):
`get_content "ipfs:QmNib9HZX2kA2jfSXq4HCSwSYyrM9Ee8aLWKiHrXQ2crmP"
{
  "id": "2.13.1",
  "author": "1.2.355",
  "co_authors": [],
  "expiration": "2017-08-03T23:59:59",
  "created": "2017-07-03T09:31:15",
  "price": {
    "map_price": [[
        1,{
          "amount": 1000000,
          "asset_id": "1.3.0"
        }
      ]
    ]
  },
  "size": 1,
  "synopsis": "{\"content_type_id\":\"0\",\"title\":\"Log-in Screen Background\",\"description\":\"[OC]\\n\\nThis is a background image for a log-in screen I made a while ago...enjoy!\"}",
  "URI": "ipfs:QmNib9HZX2kA2jfSXq4HCSwSYyrM9Ee8aLWKiHrXQ2crmP",
  "quorum": 2,
  "key_parts": [[
      "1.2.159",{
        "C1": {
          "s": "7641681771543306762617786301664413181241141702013560288636390136650075555503217544201637836420813618225889458264879674914568095525858875478806850488208334."
        },
        "D1": {
          "s": "11084211022136491456679581748555232077395306300729289131739651847359276076346086547017572992271336413931799816826934912479856373605321956102304449478793172."
        }
      }
    ],[
      "1.2.355",{
        "C1": {
          "s": "7015535072880019548360206831336368476686049735717103003206604440533997211589897341363717301673473062105776751575657584655232192361693798746592567994899720."
        },
        "D1": {
          "s": "1595628482923676857528401710170428167033000244983297065047739996837180980579305999573043681312512228907421863227083971298779606466505213346062157894247909."
        }
      }
    ],[
      "1.2.1700",{
        "C1": {
          "s": "955104471146582803920926017082284820585792182535833326144138747970086487069201521360143315153636939926465872263968980632447070389669061014456272640768555."
        },
        "D1": {
          "s": "10387539516967293057582551590598794481927169663343830562864923930411081329340149882129339027334589977121857710505788177633124288056043760010971124432411486."
        }
      }
    ]
  ],
  "_hash": "179777310e286987b215ec35691db9eae1fe2290",
  "last_proof": [[
      "1.2.355",
      "2017-07-03T09:31:20"
    ],[
      "1.2.1700",
      "2017-07-03T09:58:30"
    ]
  ],
  "is_blocked": false,
  "AVG_rating": 3000,
  "num_of_ratings": 1,
  "times_bought": 5,
  "publishing_fee_escrow": {
    "amount": 8160000,
    "asset_id": "1.3.0"
  },
  "cd": {
    "n": 435,
    "u_seed": "bd292eda559e3a44c7c781f0df262b05",
    "pubKey": "c6acebdb5f20d09608e911413485b839bc5cb402307bdc9039f2decab11fb56d01"
  }
}`

**Comment by Texxer** [comment]
my fee has been paid, the content (a few Kilobytes) ist still uploading (or never was) and it's not available to other users yet. I'm using the normal client on MB Pro 15" Retina with OSX 10.12.
