### ISSUE TITLE
My Windows Wallet Stuck & Freeze At Syncing 

### ISSUE THREAD

**Issue by super83** [DECENTfoundation/DECENT-Network#201]
I'm on Windows 10, and my wallet cannot open because it stuck at syncing, the wallet keep freezing on syncing everytime i open the wallet.

1.Error On My Windows Laptop Computer
At first i was able to download and installed and used on my laptop and send my coins to exchange, but after few days when i tried to open my wallet it stuck & freeze at syncing.....i open the wallet for hours but the syncing never ended and never download anything, it keep stuck & freezing on syncing, so it had forced closed.

2.Error On My Windows Desktop Computer
My Windows desktop, wallet also having the same problems not able to open my wallet.
Just like on my laptop, at first i was able to used the wallet on my desktop computer for few days but then the next day i cannot open my wallet, because it stuck and freeze on syncing !!!

Please help fix this problems on Windows wallet !!

![decent wallet error](https://user-images.githubusercontent.com/19049675/27902523-a594aabc-6268-11e7-99f7-535db85b45c1.png)

**Comment by Roznovjak** [comment]
Please delete hidden folder C:\Users\Name-of-the-User\AppData\Local\.decent\data and try again.

**Comment by super83** [comment]
@Roznovjak ,
Thanks...that was able to fixed my wallet problem :-)
