### ISSUE TITLE
Typing password in console is visible

### ISSUE THREAD

**Issue by D3m0nKingx** [DECENTfoundation/DECENT-Network#206]
Please consider to have the console keep the typing of the unlocking password invisible in the terminal window or shown only with asterisks (*) so for example

instead of 

`locked >>> unlock mypassword`

it should be:

`locked >>> ******` or not display any characters:  `locked >>>         `

**Comment by ejossev** [comment]
Hmm, this is tricky - you can query the database in locked mode, and you probably want to see your commands. The command itself is recognised only after it is submitted. Moreover, the libreadline keeps history of the commands... Such change would require complex redesign of cli_wallet itself :/

**Comment by D3m0nKingx** [comment]
Yes I've been using it to query while in locked mode, however for security reasons passwords really shouldn't be visible in plain text when typing them in consoles, especially in situations where running these clients on cloud vps, etc. 

In fact, when typing the unlock password in the DECENT GUI, it's only appearing as ****** .  but in regards to the cli_wallet if say for whatever reason someone steps away from their pc or mobile (using ssh, and left their phone somewhere) someone could potentitally get access.

**Comment by ejossev** [comment]
If you leave your computer screen unlocked with unlocked wallet in the console the attacker will get access regardless if the password is hidden or not?

**Comment by D3m0nKingx** [comment]
mine locks after 10 mins, but I'm speaking in general for hypothetical situations of ppl that aren't so security minded (as we've seen even the richest in crypto have had their coins stolen (https://cointelegraph.com/news/stolen-altcoins-trailed-in-augur-ethereum-hack-investigation)

**Comment by rfric** [comment]
It is fixed [here](https://github.com/DECENTfoundation/DECENT-Network/commit/b1ae7e0c80df5ac52b7fcca7b44a51c9ff9f88bf).
