### ISSUE TITLE
Can't start mining due to parsing error

### ISSUE THREAD

**Issue by sirjansel0t** [DECENTfoundation/DECENT-Network#211]
Hello,

I am trying to start mining but I am getting an error when I set miner-id below is the output.  I am using Ubuntu 16.04.

296757ms th_a       miner.cpp:90                  plugin_initialize    ] miner plugin:  plugin_initialize() begin
296757ms th_a       miner.cpp:119                 plugin_initialize    ] 4 parse_error_exception: Parse Error
Can't parse a number with two decimal places
    {}
    th_a  json.cpp:277 number_from_stream

    {"str":"1.4.183"}
    th_a  json.cpp:478 from_string
296757ms th_a       main.cpp:250                  main                 ] Exiting with error:
4 parse_error_exception: Parse Error
Can't parse a number with two decimal places
    {}
    th_a  json.cpp:277 number_from_stream

    {"str":"1.4.183"}
    th_a  json.cpp:478 from_string
rethrow
    {}
    th_a  miner.cpp:119 plugin_initialize

**Comment by Texxer** [comment]
Greetings,

You should go back to your guide and enter the data in the right format.

The console already told you what you did wrong.

I suppose this place is reserved for actual bugs, not user errors.

Kindest Regards

**Comment by sirjansel0t** [comment]
Thanks for your comment.  

I was following the wiki and it says to use the console this way:

**Comment by Texxer** [comment]
Could you try it with the config instead?

**Comment by ejossev** [comment]
The issue is that bash consumes the quotes (") - try to escape them (aka ./decentd --rpc-endpoint 127.0.0.1:8090 --miner-id \"1.4.12\" --private-key
[\"DCT7RZAJu7fLM5RS6GujZ8b9EjE3KLUzrXmAAi6QaUeiZTGHEVQXp\", \"\"]
