### ISSUE TITLE
create_package ripemd160 return 00000...

### ISSUE THREAD

**Issue by ghost** [DECENTfoundation/DECENT-Network#212]
When I try to run create_package, it seems that it does not find my file and returns 0000000
I tried from different disks, folders and files...
![iz0y3z0 1](https://user-images.githubusercontent.com/6554281/28487815-e12b242e-6e99-11e7-9158-b244329d5629.png)

**Comment by shu-iro** [comment]
Can we have some news ? about 5 days and nothing ?
It's a basic function, we just want to upload content on DECENT network, submit_content_async doesn't work for us (probably caused of create_package)

We are about to leave out of DECENT project if no news.
DECENT is in developpement since more than 6 months and the API are full of bugs, no app realy work on it and when you have a team who want help to make your project bigger, you do absolute nothing to help us...

**Comment by ejossev** [comment]
It is asynchronous call, so changed the return type to void instead of 000...0. You can check the status with search_user_content call.

**Comment by shu-iro** [comment]
It makes no sense at all.
create_package is in no way linked to an account.
And even testing as you said it does not work!
![2o2lsey 1](https://user-images.githubusercontent.com/6554281/28669844-43a2732e-72d6-11e7-9384-78613fbe1f09.png)

**Comment by ejossev** [comment]
Create_package is different command with different purpose. 
I guess there is something specific to windows, it works fine on Mac like this (assuming all preconditions are met):

unlocked >>> submit_content_async udb69358500df1e4348d478a66d6b0210 [] "/Users/josefsevcik/random.dat.512k" "" ipfs [{"region":"default", "amount":"0", "asset_symbol":"DCT"}] ["1.2.316", "1.2.3524"] "2017-07-29T22:00:00" "random data2" true

**Comment by shu-iro** [comment]
And what can I do?

**Comment by ejossev** [comment]
Try doubling the backslashes (i.e. g:\\aaa\\bbb\\ccc)

**Comment by shu-iro** [comment]
Seems to try send something but failed too
![deot76o 1](https://user-images.githubusercontent.com/6554281/28675789-30362e58-72e9-11e7-9f65-beca488d0d41.png)
![hfttxv6 1](https://user-images.githubusercontent.com/6554281/28675812-3dfdfc0a-72e9-11e7-98cc-539ce72c56f0.png)

**Comment by ejossev** [comment]
Show also the daemon output pls.

**Comment by shu-iro** [comment]
He does not print anything new
![iotyprv 1](https://user-images.githubusercontent.com/6554281/28676153-33842154-72ea-11e7-986f-642a4e9f67ec.png)

**Comment by ejossev** [comment]
decentd daemon

**Comment by shu-iro** [comment]
![5oqec3o 1](https://user-images.githubusercontent.com/6554281/28676305-9991fe94-72ea-11e7-8e5b-cc7d6523081f.png)

**Comment by ejossev** [comment]
Peter will contact you...

**Comment by shu-iro** [comment]
OK we wait

**Comment by ghbpeter** [comment]
Hello Shu-Iro, I am reading above post but I cannot catch question. Have you problem with create_package or submit_content_async ?

**Comment by shu-iro** [comment]
I can't publish content with cli_wallet on windows.

**Comment by ghbpeter** [comment]
I must to test it in our testnet, but currently it is not possible. I will check it asap. I guess that it will be some problem with input format of parameters.

**Comment by ghbpeter** [comment]
On my machine it is functional:
submit_content_async ub35c1960b34480db55fc3d859a62d4bf [] "c:\\package2\\pokus.txt" "" ipfs [{"region":"default", "amount":"0", "asset_symbol":"DCT"}] ["1.2.203", "1.2.209"] "2017-08-29T22:00:00" "pokustek" true

I can see operation with: get_account_history user limit

**Comment by shu-iro** [comment]
I'm sick of it.
You see with all my screenshots that there is a bug.
After 2 weeks of waiting you tell me everything is okay?
I am announcing that my team and I are leaving the DECENT project.

**Comment by ghbpeter** [comment]
Sorry for later answer. We work on problems by priority. I made another tests of submit_content_async in our testnet. I am not able to reproduce your problem but I found a bit different. Try please to submit content with single description with one pair of quotation marks: "my description" without defined fields: \"Name\":name,\"Description\":description...
