### ISSUE TITLE
Uploaded item is missing

### ISSUE THREAD

**Issue by DerekBess** [DECENTfoundation/DECENT-Network#220]
Two of the items I uploaded are missing. When I go to resync it shows a completely different item that I uploaded.

"BItcoin. Very great country! USA isn't number one!"

How to correct this?

**Comment by ejossev** [comment]
Hello,

I can't really tell what is the problem. Can you provide more information, like when and what exactly you did, from which account etc?

**Comment by DerekBess** [comment]
@ejossev is there a way to have a private conversation in slack or something? Every single one of my products that I uploaded are now not showing up. When I click the 3 dogs, the same message appears "BItcoin. Very great country! USA isn't number one!"

**Comment by ejossev** [comment]
my slack account is ejossev

**Comment by DerekBess** [comment]
alright, i'll message you there when i get back to the home office.
