### ISSUE TITLE
Software will not download Blockchain

### ISSUE THREAD

**Issue by ReidDecentral** [DECENTfoundation/DECENT-Network#228]
Ever since the new release "DECENT Core update 1" my DECENTcore 'Application/Software' will not sync the Blockchain. It's basically like what happened before the "Mandatory bugfixes" was required to be installed after v1.0 stopped syncing with the Blockchain.
<img width="897" alt="decentcore" src="https://user-images.githubusercontent.com/17994776/32940088-49c953de-cb47-11e7-9230-37f32def6d3d.png">
I have a 2017 MacBook Pro and I didn't upgrade to HighSierra untill yesterday [I have been slowly testing all my blockchain software on another older MacBook to test compatibility and I determined all of my crypto software was good]; only the DECENTcore wallet/software wouldnt work on either. It wouldn't work on my older MacBook because its a core2 processor but it has HighSierra [it crashes immediately]. So I had noticed that my DECENTcore wallet had stopped syncing and found the new DECENT Core update 1 and figured that would fix it [at that point I was still on Sierra]; but DECENT Core update 1 did not help the blockchain sync. So I figured it must be that DECENT Core update 1 for Mac was built for HighSierra & with all other crypto wallets and software working on HighSierra I decided to upgrade. Everything went great yet when I opened 'DECENT-distribution.1.1.0' [installation] it still isn't syncing. Then I installed 'DECENT-distribution.1.1.0-DEBUG' and that wont sync either. So it seems to me like its not an OS problem; the 'DECENT-distribution.1.1.0' wouldn't sync on Sierra and now HighSierra...

Does anyone out there have a solution for this or is experiencing the same issue?

**Comment by ejossev** [comment]
Strange... maybe you can try to run it from terminal to see where it stops:
/Applications/DECENT.app/Contents/MacOS/DECENT

**Comment by Can2Nya** [comment]
@ejossev I have same problem and use /Applications/DECENT.app/Contents/MacOS/DECENT,
log like this:

![acc808a7-a3ab-413c-8206-ef5cd5236c26](https://user-images.githubusercontent.com/10358262/34638062-40bd3bea-f2ff-11e7-9bf5-82d89c92a2dc.png)

macos sierra

**Comment by ejossev** [comment]
Sorry, been await for a while. This is clearly issue that decentd tries to attach to a port that is already in use (8090). This can be changed in ~/.decent/data/decentd/config.ini part rpc-endpoint
