### ISSUE TITLE
No binary releases for Linux x64 system

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#243]
There are no pre-compiled packages for major Linux systems. This is a issue where is a need for fast deployment.

**Comment by mpmansell** [comment]
A Docker build is being worked on that will, when released, provide for fast deployments.

**Comment by marian-decent-ch** [comment]
Suggested solution is only partial as QT wallet ain't user friendly from container. One other thing is: binary bundles are provided for GUIs on MACOSX and Windows platforms. Lastly, there always be need for full-fledged wallet: hence, QT-like that works on all PC systems. Almost every user that would like to keep his/hers anonymity boots to linux from USB stick in order to transfer funds.
