### ISSUE TITLE
Building DCore from source code

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#245]
Today, it's possible to build 3 components as a bundle: decentd, cli_wallet, qt_wallet, but not separately. As a whole it bundles a lot of unnecessary ballast, mostly for qt_wallet, that is not needed for most of the source code builds. As a result, building process takes a lot of time and it is not lightweight for DevOps, integration and containerized deployment.

This is a huge set-back in automated deployments. It is a ig issue. In addition, It is impossible to do CI/CD.

It is advised to split repository in sub-trees for each component: decentd, cli_wallet, qt_wallet. Make files requires revisions in order to optimize separate builds.

**Comment by D3m0nKingx** [comment]
``` 
cmake --build . --target all -- -j6 -l 3.0
cmake --build . --target install -- -j6
```
In the final build commands (I haven't personally tested this) but it should be possible to set the `--target all` for which component you want to build, i.e. `--target cli_wallet` ... etc.

**Comment by marian-decent-ch** [comment]
It's not working because context is given by configure step.. So, cpack is pointing somewhere else. In addition, there is zero advantage, as project need to be synced and configured as a bundle.

**Comment by marian-decent-ch** [comment]
I am closing the issue: it will be subject of enhancement proposals
