### ISSUE TITLE
README should state build steps for each distribution in turn

### ISSUE THREAD

**Issue by delatbabel** [DECENTfoundation/DECENT-Network#248]
The README file should state the build steps for each distribution in turn.  For example:

#### Ubuntu 16.10

... all build steps for Ubuntu 16.10

#### Ubuntu 16.04

... all build steps for Ubuntu 16.04

etc.

A couple of people attempting to build on Ubuntu 16.04 LTS reported to me that they missed the fact that boost version 1.60 had to be installed from source in place of the system's provided version 1.58 because that piece of information is buried later in a section headed "Ubuntu 14.04 LTS and 14.10 only" which didn't initially appear to be relevant.

**Comment by mpmansell** [comment]
We are currently in the process of updating the documentation and will take your contribution into account. 

Thanks

**Comment by rfric** [comment]
README was updated to reflect the current build requirements for each platform (Linux, MacOS, Windows).
