### ISSUE TITLE
Proposal: to rename CLI_wallet to DCore-CLIent or similar

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#255]
I am proposing to rename CLI_wallet executable to DCore-CLIent or similar, as the former name does not reflects reality: CLI_wallet executable does offer a lot more then lightweight interface for DCore daemon. It can even run in daemon mode, itself, and to offer API endpoint, voting, statistics, creating miner/seeder accounts, etc... 

Lastly, it shall be distributed and maintained as independent component. It can interface with multiple daemons and it offers plenty of deployment scenarios.

Finally, building process requires revision/optimization because it bundles a lot of unnecessary components/libraries/plugins and there is none real-release version.

**Comment by colemanik** [comment]
For now we stay with cli_wallet.
