### ISSUE TITLE
Unable to bind ethernet adapter by DCore processes

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#263]
There is no possibility to bind ethernet adapter by DCore process. E.g. I want to use separate uplink with DCore daemon (e.g. mining, p2p overlay network,...), and separate uplink via API calls or IPFS. As well as, plenty of another deployment scenarios present themselves in cloud, containerized infrastructure.

**Comment by colemanik** [comment]
Thank you for the suggestion
