### ISSUE TITLE
Blocker: Seeder nodes shall not be hardcoded in source code

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#266]
List of seeder nodes shall be publicly available on GitHub. Preferably in JSON format. During startup, daemon shall download the actual list.

There should be an API call in daemon which will commit itself into the official list. Also, It will be beneficial if these nodes send heartbeats to monitoring service (webUI with telemetry: latency, uptime, version, etc).

Other thing is that these nodes does not require most of the plugins bundled with daemon. Also, it does not require to hold blockchain copy. Seeder nodes are very important in an infrastructure, so why not make them as lightweight and cheep as possible?

The hardcoded list have DNS names that could be easily spoofed what could in theory lead to 51% attack. As well as, they could be used for DDoS attack. Lastly, it does not look trustworthy.

I know it could be overridden via config.ini so the question is: why not distribute config.ini within official bundles?

**Comment by colemanik** [comment]
Thank you for the suggestion
