### ISSUE TITLE
Seeder nodes shall distribute blockchain snapshot

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#267]
While actual blockchain state is downloaded from nodes that are brokered by initial seeder node, it takes a long time to get in sync. The problem is that daemon establish initial connection with seeder node by iterating through the list and not by latency, uplink, geo-location. Seeder then establishes overlay network with daemons based on availability, latency, and so on (DHT). It is good design for small files but not for huge files. It is recommended to use seeder nodes to push last hour snapshot as compressed file using octet-stream. Afterward, daemon will start with replay option.

**Comment by colemanik** [comment]
Thank you for the suggestion
