### ISSUE TITLE
Implement concept of Segregated Witness

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#273]
As the memory requirements grows with each block, in time. In cloud deployments or high-performance-computing, a space efficiency is the important property, in order to keep used memory as low as possible, the segregated witness approach shall be implemented. The basic idea behind, is the fact that once the transaction is validated and it is immutable written into a blockchain database, its signature is no longer relevant. Therefore, these signatures shall be omitted from blockchain space.

**Comment by colemanik** [comment]
Thank you for the suggestion
