### ISSUE TITLE
Flexible versioning, feature set, releasing cycles of core blockchain application

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#278]
In order to have widespread outreach of blockchain application, it requires constant development and support of community which provides base for whole application and building blocks for consensus and infrastructure. The development team provides functional and security updates that will enrich and refine user's experience.

In return, users need to be part of the process. Therefore, it is required to have constant release cycles with pre-known versioning and finalized feature set that is discussed and presented upfront with the community. In order to prepare for release upgrade, SW need to be tested, as well as, miners need to prepare themselves for smooth upgrades. Lastly, everything aforementioned, requires to gain upfront community support.

The issue is that such a process seems to be non-existing.

**Comment by colemanik** [comment]
Thank you for the suggestion
