### ISSUE TITLE
Missing options for hot/cold storage threshold for blockchain database

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#281]
There is none option switch for setting hot/cold storage threshold (shared memory) based on criteria to track account history:

- interval from now, e.g. keep last month in memory, or from date of account creation
- selected number of operations for all accounts
- track chosen accounts and keep only selected number of previous operations
- track only chosen accounts
- and so on

Also, it shall be implemented as cmake macro.

**Comment by colemanik** [comment]
Thank you for the suggestion
