### ISSUE TITLE
Missing database options for miners

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#282]
Miners as a block producers and transaction validators, do not need to keep whole blockchain copy in memory. They need only necessary data to produce block and validate transactions. The other issue is that cold stored db copy can be mounted over network as read-only for necessary data. Live and writable data are then stored in memory until broadcasted.

Also, it shall be implemented as cmake macro.

**Comment by colemanik** [comment]
Thank you for the suggestion
