### ISSUE TITLE
Missing option to run node with sole purpose

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#289]
It shall be preferred that node full-fills one purpose: 

if it is miner, it shall not have API endpoint, seeding (ipfs proxy), necessary data for mining from blockchain history preloaded in memory, and other unnecessary plugins
if it is seed node, mining, it shall not have API endpoint, seeding (ipfs proxy), no blockchain data preloaded in memory, and other unnecessary plugins
if it is seeding node, it shall not have mining, API endpoint, necessary data for seeding from blockchain history preloaded in memory, and other unnecessary plugins
if it is API node, it shall not have mining, seeding, whole history preloaded in memory or nothing preloaded in memory but recorded in elasticsearch (redis), etc.

It is required for scalable, on-demand deployments with load-balancer and workers. As well as, for containerized cloud deployments.

**Comment by colemanik** [comment]
Thank you for the suggestion
