### ISSUE TITLE
Implement Elasticsearch or Redis history plugin

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#290]
It is preferable to have history plugin implemented in different in-memory database as are boost-objects, mostly because of indexing and to offer more scalable database endpoint in clustered setup that is accessible via well-established client-side connectors. The idea is to have blockchain copy coldly stored and during replay, history data will be committed to the elastic/redis database cluster.

**Comment by colemanik** [comment]
Thank you for the suggestion
