### ISSUE TITLE
Implement message queues client in daemon

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#294]
In order to allow scaling, there is a need for workers nodes. These require scheduling via broker, and to leverage topics for notifies and to cache recurrent responses. Also, it opens a way for other interactions and integrations with DCore, hence to accelerate development of tools and depending services.

**Comment by MilanFranc** [comment]
@marian-decent-ch you can implement this ideas in your copy of DECENT-Network source code.
