### ISSUE TITLE
Missing multi-signature protection for account/wallet

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#295]
There has never been enough protection for your account, and it will never be: the multi-signature approach mitigates some of the attacks and improves user experience in case of partial lost of keys.

**Comment by ejossev** [comment]
It would be really helpful, and save quite some time of all involved, if you spend some time studying something before pushing new proposals, instead of copying random ideas from the internet to pretend activity. DECENT support even more advanced account management than just multisigs.

**Comment by marian-decent-ch** [comment]
Different people have different opinions. If you don't like it then dismiss it. Not everything is about besting but usability and user's experience. By the way, this idea is based on security lecture on protection for blockchain accounts.
