### ISSUE TITLE
Reindex console output does not go via logger

### ISSUE THREAD

**Issue by marian-decent-ch** [DECENTfoundation/DECENT-Network#356]
In daemon mode, it would be beneficial to have replay feedback -> console output does not go via logger:

         if (i % 2000 == 0) std::cerr << "   " << _reindexing_percent << "%   " << i << " of " << last_block_num << "   \n";
fc::optional< signed_block > block = _block_id_to_block.fetch_by_number(i);

**Comment by rfric** [comment]
You are right, will be fixed in #357.
