### ISSUE TITLE
"create_account_with_brain_key" command is used？

### ISSUE THREAD

**Issue by tzdadada** [DECENTfoundation/DECENT-Network#421]
Where do "ACCOUNT_NAME" and "PRIVATE_KEY" in "LoginExample" in "java Example" come from? How should I create my first account? How the "create_account_with_brain_key" command is used. . . . . Please help me ~

**Comment by Roznovjak** [comment]
You should be able to find all the answers in the documentation [https://docs.decent.ch](url).
